# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Feature Request
description: Issue to track a Feature Request
title: "Your Feature Request title"
labels: ["codeowner_review"]
type: 'Feature Request'
body:
  - type: markdown
    attributes:
      value: "## <ins>Feature Request Ticket creation</ins>"
  - type: textarea
    attributes:
      label: Feature Request Description
      description: |
        - Use following template within a PR and link it to this issue
          [Change Management Feature Request Template](https://eclipse-score.github.io/process_description/main/process_areas/change_management/guidance/change_management_feature_template.html) needs to be used
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Expected available in Release 
      options:
        - '1.0'
        - '2.0'
        - '3.0'
      default: 0
    validations:
      required: false
