# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Component Request
description: Issue to track a Component Request
title: "Your Component Request title"
labels: ["codeowner_review"]
type: 'Component Request'
body:
  - type: markdown
    attributes:
      value: "## <ins>Component Request Ticket creation</ins>"
  - type: textarea
    attributes:
      label: Component Request Description
      description: |
       - Follow the [Change Management Workflow](https://eclipse-score.github.io/score/main/platform_management_plan/change_management.html#change-request-workflow) 
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Expected Implementation Version (Release)
      options:
        - '1.0'
        - '2.0'
        - '3.0'
      default: 0
    validations:
      required: false