# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Product Increment
description: Issue to track a Product Increment
title: "Your Product Increment title"
labels: ["codeowner_review"]
type: 'Product Increment'
body:
  - type: markdown
    attributes:
      value: "## <ins>Product Increment Ticket creation</ins>"
  - type: textarea
    attributes:
      label: Product Increment Description
      description: |
         - New Functionality / Features
         - API changes 
         - Major Fixes 
    validations:
      required: true
  - type: textarea
    attributes:
      label: Acceptance Criteria (DoD)
      description: Details on when the Product Increment is considered "done"
    validations:
      required: true
  