# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Epic
description: Issue to track an Epic
title: "Your Epic title"
labels: ["codeowner_review"]
type: 'Epic'
body:
  - type: markdown
    attributes:
      value: "## <ins>Epic Ticket creation</ins>"
  - type: textarea
    attributes:
      label: Epic Description
      description: Goal of the Epic
    validations:
      required: true
  - type: textarea
    attributes:
      label: Acceptance Criteria (DoD)
      description: Details on when the Task is considered "done"
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Affects work products
      options:
        - label: Requirements
        - label: Architecture
        - label: Safety Analysis
        - label: Security Analysis 
        - label: Detailed Design
        - label: Implementation 
        - label: Test Cases
        - label: Process
        - label: Infrastructure
        - label: Others
          required: true
