# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Task
description: Issue to track a Task
title: "Your Task title"
labels: ["codeowner_review"]
type: Task
body:
  - type: markdown
    attributes:
      value: "## <ins>Task Ticket creation</ins>"
  - type: textarea
    attributes:
      label: What
      description: |
        - Goal of the Task
    validations:
      required: true
  - type: textarea
    attributes:
      label: Acceptance Criteria (DoD)
      description: Details on when the Task is considered "done"
    validations:
      required: true
  - type: textarea
    attributes:
      label: How
      description: Details on implementation approach
    validations:
      required: false
