# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Bug
description: Issue to track a Bug
title: "Your Bug title"
labels: ["codeowner_review"]
type: 'Bug'
body:
  - type: markdown
    attributes:
      value: "## <ins>Bug Ticket creation</ins>"
  - type: textarea
    attributes:
      label: Description
      description: |
        Description of the Bug
        Root cause / Impact / Notification required?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Analysis results
      description: |
        Documentation of the analysis results
    validations:
      required: false
  - type: textarea
    attributes:
      label: Solution
      description: |
        Documentation of the solution
        Link to Pull Request containing the solution
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Error Occurrence  Rate
      options:
        - Single Event
        - Sporadic
        - Highly Intermittent
        - Reproducible
  - type: textarea
    attributes:
      label: How to reproduce
      description: How to reproduce?
  - type: textarea
    attributes:
      label: Supporting Information
      description: |
        During which operational state did the issue occur
        Observations / Screenshots / Traces
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Classification
      options:
        - Minor
        - Major
        - Critical
        - Blocker
      default: 0
    validations:
      required: true
  - type: dropdown
    attributes:
      label: First Affected Release 
      options:
        - not released (main)        
        - pre-0.5
        - 0.5
        - 0.6
        - 0.7
        - 0.8
        - 0.9
        - 1.0
      default: 0
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Last Affected Release 
      options:
        - not released (main)        
        - pre-0.5
        - 0.5
        - 0.6
        - 0.7
        - 0.8
        - 0.9
        - 1.0
      default: 0
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Expected Fixed Release
      options:
        - before release (main)        
        - 0.5
        - 0.6
        - 0.7
        - 0.8
        - 0.9
        - 1.0
      default: 0
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Category
      options:
        - label: Safety Relevant
        - label: Security Relevant
  - type: dropdown
    attributes:
      label: ASIL classification
      options:
        - QM
        - ASIL_B
        - ASIL_D
      default: 0
    validations:
      required: false
