"""Compatibility façade for the policy-sync report integration."""

from .policy_sync import (
    POLICY_REPORT_FILENAME,
    POLICY_REPORT_SCHEMA_VERSION,
    PolicyReport,
    PolicyReportOutcome,
    PolicyReportSummary,
    PolicySyncChange,
    PolicySyncOutcome,
    PolicySyncReport,
    PolicySyncSummary,
    fetch_policy_report,
    fetch_policy_sync_report,
    load_policy_descriptions,
    load_policy_report,
    load_policy_sync_report,
    parse_policy_report,
    parse_policy_sync_report,
    policy_sync_report_to_dict,
    render_policy_sync_report_json,
    render_policy_sync_section,
)

__all__ = [
    "POLICY_REPORT_FILENAME",
    "POLICY_REPORT_SCHEMA_VERSION",
    "PolicyReport",
    "PolicyReportOutcome",
    "PolicyReportSummary",
    "PolicySyncChange",
    "PolicySyncOutcome",
    "PolicySyncReport",
    "PolicySyncSummary",
    "fetch_policy_report",
    "fetch_policy_sync_report",
    "load_policy_descriptions",
    "load_policy_report",
    "load_policy_sync_report",
    "parse_policy_report",
    "parse_policy_sync_report",
    "policy_sync_report_to_dict",
    "render_policy_sync_report_json",
    "render_policy_sync_section",
]
