name: Daily Maintenance

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write
  pages: write
  id-token: write
  actions: write

jobs:
  daily:
    uses: eclipse-score/cicd-workflows/.github/workflows/daily.yml@37eaadadfefc263d94a858d25665735659e916fa # main (2026-09-02)
