name: Update Repository States

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - run: pip install -r requirements.txt

      - name: Update README
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: python scripts/update_readme.py


      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: Update status
          author: eclipse-score-bot <187756813+eclipse-score-bot@users.noreply.github.com>
          committer: eclipse-score-bot <187756813+eclipse-score-bot@users.noreply.github.com>
          body: |
            This PR updates the description and status columns of the start page.
            Please review and merge if everything looks good.
          commit-message: "chore: auto-refresh status column"
          # We need to use a different token than GITHUB_TOKEN, so that PR triggers all the PR-workflows.
          branch: bot/status-update
        env:
          GITHUB_TOKEN: ${{ secrets.SCORE_BOT_PAT }}
